#include <clang-c/Index.h>

#include <cstring>
#include <functional>
#include <iostream>
#include <vector>

struct Entry {
  std::string name;
  std::vector<std::string> literals;
};

static int FindEntry(const std::vector<Entry>& entries, const char* name) {
  for (size_t i = 0; i < entries.size(); ++i)
    if (std::strcmp(entries[i].name.c_str(), name) == 0) return i;
  return -1;
}

std::vector<Entry> entries;

std::vector<const char*> wanted;

static bool WantedEnum(std::vector<const char*> wanted, const char* name) {
  for (auto e : wanted)
    if (std::strcmp(e, name) == 0) return true;
  return false;
}

static CXChildVisitResult visitor(CXCursor cursor, CXCursor parent,
                                  CXClientData client_data) {
  auto kind = clang_getCursorKind(cursor);

  // {
  //   auto spelling = clang_getCursorSpelling(cursor);
  //   auto kindSpelling = clang_getCursorKindSpelling(kind);
  //   std::printf("%s, %s, %d\n", clang_getCString(spelling),
  //               clang_getCString(kindSpelling), kind);
  //   clang_disposeString(spelling);
  //   clang_disposeString(kindSpelling);
  // }

  switch (kind) {
    case CXCursorKind::CXCursor_EnumDecl: {
      if (clang_EnumDecl_isScoped(cursor)) {
        auto spelling = clang_getCursorSpelling(cursor);
        auto kindSpelling = clang_getCursorKindSpelling(kind);

        if (WantedEnum(wanted, clang_getCString(spelling))) {
          entries.push_back(Entry{clang_getCString(spelling), {}});
        }

        clang_disposeString(spelling);
        clang_disposeString(kindSpelling);
      }

    } break;
    case CXCursorKind::CXCursor_EnumConstantDecl: {
      auto parentSpelling = clang_getCursorSpelling(parent);

      auto i = FindEntry(entries, clang_getCString(parentSpelling));
      if (i != -1) {
        auto spelling = clang_getCursorSpelling(cursor);

        entries[i].literals.push_back(clang_getCString(spelling));

        clang_disposeString(spelling);
      }

      clang_disposeString(parentSpelling);
    } break;
    default:
      break;
  }

  return CXChildVisit_Recurse;
}

struct Flag {
  const char* name{nullptr};
  bool active{false};
  char* value{nullptr};
};

static const char* fNamespace = "--namespace";
static const char* fIncludeGuard = "--include-guard";

static Flag gFlags[]{
    Flag{fNamespace},
    Flag{fIncludeGuard},
};
static const size_t gFlagsLen = sizeof(gFlags) / sizeof(Flag);

static Flag* FindFlag(const char* name, int n) {
  if (n == -1) n = strlen(name);
  for (size_t i = 0; i < gFlagsLen; ++i) {
    if (strncmp(name, gFlags[i].name, n) == 0) return &gFlags[i];
  }
  return nullptr;
}

static std::pair<int, char**> parseFlags(int argc, char** argv) {
  int n = 0;
  for (int i = 1; i < argc; ++i) {
    if (strncmp(argv[i], "--", 2) != 0) {
      // not a flag
      break;
    }
    auto sep = strchr(argv[i], '=');
    if (sep == nullptr) {
      std::fprintf(stderr, "flag '%s' has wrong format, must be --name=value\n",
                   argv[i]);
      exit(1);
    }
    const auto nameLen = sep - argv[i];
    auto f = FindFlag(argv[i], nameLen);
    if (f == nullptr) {
      argv[i][nameLen] = 0;
      std::fprintf(stderr, "unknown flag %s\n", argv[i]);
      exit(1);
    }
    f->active = true;
    f->value = sep + 1;
    ++n;
  }
  return {argc - n, argv + n};
}

int main(int argc, char** argv) {
  std::tie(argc, argv) = parseFlags(argc, argv);

  if (argc < 2) {
    std::fprintf(stderr, "missing input file\n");
    return 1;
  }

  if (argc < 3) {
    std::fprintf(stderr, "missing enum name(s)\n");
    return 1;
  }

  for (auto i = 2; i < argc; ++i) {
    wanted.push_back(argv[i]);
  }

  auto index = clang_createIndex(0, 0);

  auto translationUnit = clang_parseTranslationUnit(
      index, argv[1], nullptr, 0, nullptr, 0, CXTranslationUnit_None);
  if (translationUnit == nullptr) {
    std::cerr << "Unable to parse translation unit. Quitting.\n";
    return 1;
  }

  auto cursor = clang_getTranslationUnitCursor(translationUnit);
  clang_visitChildren(cursor, visitor, nullptr);

  auto namespaceFlag = FindFlag(fNamespace, -1);
  auto inGuardFlag = FindFlag(fIncludeGuard, -1);

  printf(
      "// GENERATED by enum2s tool, DO NOT EDIT!!! EVERYTHING YOU CHANGE WILL "
      "BE OVERWRITTEN!!!\n\n");

  if (inGuardFlag->active) {
    printf("#ifndef %s\n#define %s\n\n", inGuardFlag->value,
           inGuardFlag->value);
  }
  if (namespaceFlag->active) {
    printf("namespace %s {\n", namespaceFlag->value);
  }

  for (const auto& entry : entries) {
    printf("\nstatic const char* const * EnumNames_%s[] = {\n",
           entry.name.c_str());
    for (const auto& literal : entry.literals)
      printf("    \"%s\",\n", literal.c_str());
    printf("};\n\n");

    printf(
        "inline const char* EnumName_%s(%s v)\n"
        "{\n"
        "    if (v < %s::%s || v > %s::%s)\n"
        "        return \"\";\n"
        "    const size_t index = static_cast<size_t>(v - %s::%s);\n"
        "    return EnumNames_%s[index];\n"
        "}\n",
        entry.name.c_str(), entry.name.c_str(), entry.name.c_str(),
        entry.literals.front().c_str(), entry.name.c_str(),
        entry.literals.back().c_str(), entry.name.c_str(),
        entry.literals.front().c_str(), entry.name.c_str());
  }

  if (namespaceFlag->active) {
    printf("\n} // %s\n", namespaceFlag->value);
  }
  if (inGuardFlag->active) {
    printf("\n#endif\n");
  }

  clang_disposeTranslationUnit(translationUnit);
  clang_disposeIndex(index);
}
